"""The plan <-> parameter <-> device map, generated from a live queueserver.

    planrunner-map --server http://localhost:60610 --api-key KEY \\
        --source ~/git_projects/hex-profile-collection --output plan-device-map.md

For every allowed plan: each parameter, its type (declared, or guessed and marked
'?'), the devices that can fill it; and the devices the plan uses without a
parameter, from its local source. Then the inverse: for every device, the plans
that can use it. Generated, never hand-maintained, so it cannot drift from the
profile it describes.
"""

import argparse
import json
import sys
import time
from collections import defaultdict
from collections.abc import Mapping, Sequence
from dataclasses import asdict, dataclass, field
from pathlib import Path

from planrunner.hidden_deps import HiddenDependency, How, hidden_dependencies
from planrunner.plan_groups import source_of
from planrunner.plan_params import Catalog, FieldKind, ParamKind, describe_plan
from planrunner.protocols import JSON
from planrunner.source_types import annotations_in
from planrunner.sources import SourceFinder


@dataclass(frozen=True, slots=True)
class ParamRow:
    name: str
    type_label: str
    declared: bool
    """False when the plan declares no type and planrunner guessed."""
    devices: tuple[str, ...] = ()
    components: int = 0
    """How many device components may be chosen instead of a whole device."""


@dataclass(frozen=True, slots=True)
class PlanMap:
    name: str
    group: str
    params: tuple[ParamRow, ...]
    hidden: tuple[HiddenDependency, ...] = ()
    source: str = ""


@dataclass(slots=True)
class DeviceUse:
    parameters: list[str] = field(default_factory=list)
    hidden: list[str] = field(default_factory=list)


def build_map(plans: Mapping[str, JSON], catalog: Catalog,
              finder: SourceFinder | None = None) -> list[PlanMap]:
    maps = []
    for name in sorted(plans):
        plan = plans[name]
        found = finder.find(name, plan.get("module")) if finder is not None else None
        spec = describe_plan(plan, catalog, annotations_in(found.text) if found else None)
        rows = []
        for p in spec.params:
            is_device = p.device_capability is not None or (
                p.field_kind in (FieldKind.CHOICE, FieldKind.MULTI_CHOICE) and
                bool(set(p.choices) & set(catalog.devices)))
            rows.append(ParamRow(
                name=_display_name(p.name, p.kind),
                type_label=p.type_label,
                declared=not p.converts_names,
                devices=p.choices if is_device else (),
                components=sum(len(c) for c in p.component_choices.values()),
            ))
        hidden: tuple[HiddenDependency, ...] = ()
        where = ""
        if found is not None:
            # A look-up "when not passed" is not hidden when the parameter declares a
            # device default: the queueserver shows that default and passes it itself.
            defaulted = {p.name for p in spec.params
                         if isinstance(p.default, str) and p.default in catalog.devices}
            hidden = tuple(
                d for d in hidden_dependencies(found.text, catalog.devices)
                if not (d.how is How.LOOKUP_IF_NOT_PASSED and d.device in defaulted)
            )
            where = f"{found.path}:{found.first_line}"
        maps.append(PlanMap(name, source_of(plan), tuple(rows), hidden, where))
    return maps


def device_index(maps: Sequence[PlanMap]) -> dict[str, DeviceUse]:
    uses: dict[str, DeviceUse] = defaultdict(DeviceUse)
    for plan in maps:
        for row in plan.params:
            for device in row.devices:
                uses[device].parameters.append(f"{plan.name}.{row.name}")
        for dep in plan.hidden:
            uses[dep.device].hidden.append(plan.name)
    return dict(sorted(uses.items()))


def render_markdown(maps: Sequence[PlanMap], catalog: Catalog, server: str) -> str:
    stamp = time.strftime("%Y-%m-%d %H:%M")
    untyped = sum(1 for m in maps for r in m.params if not r.declared)
    total = sum(len(m.params) for m in maps)
    lines = [
        "# Plan ↔ parameter ↔ device map",
        "",
        f"Generated by `planrunner-map` from **{server}** at {stamp}: "
        f"{len(maps)} plans, {len(catalog.devices)} top-level devices. "
        f"**{untyped} of {total} parameters declare no type**; their types below are "
        "planrunner's guesses, marked `?`. Regenerate rather than edit.",
        "",
    ]
    for group in sorted({m.group for m in maps}):
        lines += [f"## {group}", ""]
        for m in (m for m in maps if m.group == group):
            lines += [f"### `{m.name}`", ""]
            if m.source:
                lines += [f"Source: `{m.source}`", ""]
            lines += ["| Parameter | Type | Devices that can fill it |", "|---|---|---|"]
            for row in m.params:
                devices = ", ".join(f"`{d}`" for d in row.devices) or "—"
                if row.components:
                    devices += f" (or one of {row.components} components)"
                lines.append(f"| `{row.name}` | {row.type_label} | {devices} |")
            if m.hidden:
                lines += ["", "**Uses without a parameter** (not visible to any client):"]
                lines += [f"- `{d.device}`: {d.how.value} (line {d.line} of the plan)"
                          for d in m.hidden]
            lines.append("")
    lines += ["## By device", "", "| Device | Class | Can fill | Used without a parameter by |",
              "|---|---|---|---|"]
    index = device_index(maps)
    for name in catalog.devices:
        use = index.get(name, DeviceUse())
        node = catalog.tree.get(name)
        lines.append(
            f"| `{name}` | {node.classname if node else ''} | "
            f"{', '.join(f'`{p}`' for p in use.parameters) or '—'} | "
            f"{', '.join(f'`{p}`' for p in use.hidden) or '—'} |"
        )
    extra = sorted(set(index) - set(catalog.devices))
    if extra:
        lines += ["", "Looked up by name but not among the allowed devices: "
                  + ", ".join(f"`{e}`" for e in extra)]
    return "\n".join(lines) + "\n"


def _display_name(name: str, kind: ParamKind) -> str:
    match kind:
        case ParamKind.VAR_POSITIONAL:
            return f"*{name}"
        case ParamKind.VAR_KEYWORD:
            return f"**{name}"
        case _:
            return name


# --- Command line ---------------------------------------------------------------


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(prog="planrunner-map", description=__doc__.splitlines()[0])
    parser.add_argument("-s", "--server", required=True, help="bluesky-httpserver address")
    parser.add_argument("-k", "--api-key", help="API key (needed to read plans and devices)")
    parser.add_argument("--source", action="append", default=[], metavar="PATH",
                        help="local checkout to read plan source from; repeat for several")
    parser.add_argument("-o", "--output", default="plan-device-map.md", help="Markdown report")
    parser.add_argument("--json", help="also write the map as JSON to this path")
    args = parser.parse_args(argv)

    from bluesky_queueserver_api.http import REManagerAPI  # noqa: PLC0415 - heavy import

    api = REManagerAPI(http_server_uri=args.server)
    if args.api_key:
        api.set_authorization_key(api_key=args.api_key)
    try:
        plans = api.plans_allowed(reload=True)["plans_allowed"]
        devices = api.devices_allowed(reload=True)["devices_allowed"]
    finally:
        api.close()

    catalog = Catalog.from_allowed(devices, plans=plans)
    maps = build_map(plans, catalog, SourceFinder([Path(p) for p in args.source]))
    Path(args.output).write_text(render_markdown(maps, catalog, args.server))
    if args.json:
        Path(args.json).write_text(json.dumps([asdict(m) for m in maps], indent=2))
    print(f"Wrote {args.output}: {len(maps)} plans, {len(catalog.devices)} devices",
          file=sys.stderr)


if __name__ == "__main__":
    main()
