#!/usr/bin/env python3
# Python-3 PandA hardware-simulation daemon for the HEX sim (Option C).
#
# Background
# ----------
# The PandABlocks-server `simserver` normally launches its *bundled* register
# simulator (`server/python/sim_server`), which is "as dumb as a brick": it
# implements the register read/write protocol but runs NO block timing logic.
# That is why CLOCK/PCOMP/PULSE/PCAP never tick and PCAP:ACTIVE never latches,
# so an ophyd-async fly scan (arm -> wait pcap.active -> capture) stalls.
#
# PandABlocks-FPGA ships a *real* cycle-accurate block-simulation engine in
# `common/python/simulations.py` (SimulationController + per-block `*_sim.py`
# models). Its `generate_app` step also emits an autogenerated `sim_server`
# that wires the engine up to the register socket the C server talks to -- but
# that generated script is Python 2 (`print` statements) and the socket layer
# in `simulations.py` still uses Python-2 byte handling, so it will not run
# under the container's `python3`.
#
# This wrapper reuses the (Python-3 clean) `SimulationController` engine and
# per-block models unchanged, and reimplements ONLY the thin register socket
# loop in correct Python 3. It is dropped in as `<dir>/autogen/sim_server` and
# selected via `simserver -f <dir>`.
#
# Block list mirrors the autogen sim_server for the `pandabox-no-fmc` app,
# minus the two `sfp_panda_sync` blocks: those require FPGA pin-constraint
# metadata (`site_LOC`) that is absent for a soft build, and they are unused by
# tomography fly scans. Register reads to their (dropped) addresses fall through
# to the controller's graceful default of 0.

import argparse
import configparser
import os
import re
import select
import socket
import struct
import sys
import time

import numpy as np

# ---- Locate the PandABlocks-FPGA source tree so we can import the engine ----
# Baked in by the Dockerfile; falls back to the conventional autogen layout
# (<root>/build/apps/<app>/autogen/sim_server -> <root> is four levels up).
_FPGA_ROOT = os.environ.get("PANDA_FPGA_ROOT")
if not _FPGA_ROOT:
    _FPGA_ROOT = os.path.abspath(
        os.path.join(os.path.dirname(__file__), "..", "..", "..", "..")
    )
sys.path.insert(0, _FPGA_ROOT)

from common.python.simulations import (  # noqa: E402
    CLOCK_TICK,
    BlockSimulation,
    SimulationController,
    daemonise,
)

# The engine schedules wakeups as (ts, block, changes) tuples and inserts them
# with bisect. When two wakeups share a timestamp -- which happens as soon as a
# position change fans out to more than one listener (e.g. INENC.VAL -> both
# PCOMP.INP and PCAP) -- bisect tries to order the block instances and raises
# TypeError (blocks aren't comparable). The block-timing tests never hit this
# (they drive a single block in isolation). Give blocks a stable id-based order
# so equal-timestamp wakeups sort deterministically without touching the engine.
BlockSimulation.__lt__ = lambda self, other: id(self) < id(other)


# ---- Engine wakeup-merge patches -------------------------------------------
# The stock engine LOSES pending wakeup changes whenever two changes collide on
# one block, in three places:
#
#   1. `do_tick` schedule loop: a listener block with a queued wakeup that
#      carries changes (e.g. PCOMP holding ENABLE=1 fanned out from a BITS.A
#      write) has that wakeup removed and replaced when a new change arrives
#      (e.g. INP from a position injection) -- the queued ENABLE is dropped, so
#      PCOMP/PULSE/PCAP silently never enable. With a bridge injecting
#      positions continuously this is not a race but a certainty.
#   2. `do_tick` due-wakeup loop: `block_changes.setdefault(...)` discards the
#      due wakeup's changes if the same block also has direct changes this tick.
#   3. `process_blocks`: a block receiving direct changes has its pending
#      wakeup dropped via `remove_wakeup`.
#
# `remove_wakeup` itself is also unusable here: it bisects with a
# (ts, None, None) probe that raises TypeError comparing None against a block
# whenever timestamps collide, and asserts the popped wakeup carries no
# changes. The replacements below MERGE colliding changes (newest value wins
# per field, nothing is dropped) and pop pending wakeups with a linear scan
# (the list holds at most one entry per block).


def _pop_pending_wakeup(controller, block):
    """Remove ``block``'s queued wakeup and return the changes it carried."""
    old_ts = controller.next_wakeup.pop(block, None)
    if old_ts is None:
        return None
    for i, (_w_ts, w_block, w_changes) in enumerate(controller.wakeups):
        if w_block is block:
            controller.wakeups.pop(i)
            return w_changes
    return None


def _merging_do_tick(self, block_changes=None):
    ts = int((time.time() - self.start_time) / CLOCK_TICK)
    if block_changes is None:
        block_changes = {}
    # If we have a wakeup, then make sure we aren't going back in time
    if self.wakeups:
        wake_ts, _, _ = self.wakeups[0]
        if ts > wake_ts:
            ts = wake_ts
    # Merge every wakeup due at this ts into block_changes (never drop either)
    while self.wakeups and self.wakeups[0][0] == ts:
        _w_ts, wake_block, wake_changes = self.wakeups.pop(0)
        self.next_wakeup[wake_block] = None
        if wake_block in block_changes:
            merged = dict(wake_changes)
            merged.update(block_changes[wake_block])
            block_changes[wake_block] = merged
        else:
            block_changes[wake_block] = wake_changes
    new_wakeups = self.process_blocks(ts, block_changes)
    # Re-schedule, folding any still-queued changes into the new wakeup
    for (block, wakeup), changes in new_wakeups.items():
        pending = _pop_pending_wakeup(self, block)
        if pending:
            merged = dict(pending)
            merged.update(changes)
            changes = merged
        self.insert_wakeup(wakeup, block, changes)


def _merging_process_blocks(self, ts, block_changes):
    # map block -> changes
    new_wakeups = {}
    pos_changes = []
    for block, changes in block_changes.items():
        # Fold the block's queued-but-not-yet-delivered changes in ahead of
        # the new ones instead of discarding them with its wakeup.
        pending = _pop_pending_wakeup(self, block)
        if pending:
            merged = dict(pending)
            merged.update(changes)
            changes = merged
        next_ts = block.on_changes(ts, changes)
        # PULSE-train fix: pulse_sim tracks its next edge in `edge_ts` but its
        # on_changes only ever returns queue-head times, never edge_ts — on
        # real FPGA every clock processes, but this event-driven server only
        # calls a block at its returned wakeup, so a started train emits its
        # first edge and then dies. Duck-typed on purpose: any block modelling
        # a pending edge this way gets woken for it.
        if getattr(block, "edges_remaining", 0):
            edge_ts = getattr(block, "edge_ts", None)
            if edge_ts is not None and edge_ts > ts and \
                    (next_ts is None or edge_ts < next_ts):
                next_ts = edge_ts
        # Update bit_bus and pos_bus
        for attr, val in block.changes.items():
            data = self.bus_lookup.get((block, attr), None)
            if data is None:
                continue
            bus, bus_changes, idx = data
            if bus is BlockSimulation.pos_bus:
                pos_changes.append(idx)
            bus[idx] = val
            bus_changes[idx] = 1
            # If someone's listening, tell them about it
            for lblock, lattr in self.listeners.get((block, attr), []):
                dly = self.delays.get((lblock, lattr), 0)
                new_wakeups.setdefault((lblock, ts + 1 + dly), {})[lattr] = val
        # Reset the changed attributes dict
        block.changes = {}
        # If we are due to be woken up, add this one to the wakeup dict
        if next_ts is not None:
            new_wakeups.setdefault((block, next_ts), {})
    if pos_changes:
        new_wakeups.setdefault((self.pcap, ts + 1), {})["POS_BUS"] = \
            pos_changes
    return new_wakeups


SimulationController.do_tick = _merging_do_tick
SimulationController.process_blocks = _merging_process_blocks

# Blocks that cannot be simulated in a soft (no-FPGA) build: they need pin
# constraint metadata (`site_LOC`) that is only present for a hardware target.
# They are unused by tomography fly scans; reads to their addresses fall through
# to the controller's graceful default of 0.
UNSUPPORTED_BLOCKS = {"sfp_panda_sync"}

# Fallback block list for the `pandabox-no-fmc` app, used only if the original
# generated sim_server cannot be parsed. (ini_path relative to FPGA root,
# instance count, block address); order/addresses must match config_d.
FALLBACK_BLOCKS = [
    ("modules/ttlin/ttlin.block.ini", 6, 2),
    ("modules/ttlout/ttlout.block.ini", 10, 3),
    ("modules/lvdsin/lvdsin.block.ini", 2, 4),
    ("modules/lvdsout/lvdsout.block.ini", 2, 5),
    ("modules/inenc/inenc.block.ini", 4, 6),
    ("modules/outenc/outenc.block.ini", 4, 7),
    ("modules/pcap/pcap.block.ini", 1, 8),
    ("modules/system/system.block.ini", 1, 9),
    ("modules/bits/bits.block.ini", 1, 10),
    ("modules/calc/calc.block.ini", 2, 11),
    ("modules/clock/clock.block.ini", 2, 12),
    ("modules/counter/counter.block.ini", 8, 13),
    ("modules/div/div.block.ini", 2, 14),
    ("modules/filter/filter.block.ini", 2, 15),
    ("modules/lut/lut.block.ini", 8, 16),
    ("modules/pcomp/pcomp.block.ini", 2, 17),
    ("modules/pulse/pulse.block.ini", 4, 18),
    ("modules/seq/seq.block.ini", 2, 19),
    ("modules/pgen/pgen.block.ini", 2, 20),
    ("modules/srgate/srgate.block.ini", 4, 21),
]

# `controller.create_block("modules/pcap/pcap.block.ini", 1, 8)`
_CREATE_BLOCK_RE = re.compile(
    r"""create_block\(\s*["']([^"']+)["']\s*,\s*(\d+)\s*,\s*(\d+)\s*\)"""
)


def load_blocks():
    """Return the (ini_path, number, address) block list for the sim.

    Prefer the create_block() calls in the original generated sim_server so the
    simulated block set always matches config_d; fall back to a static list.
    Unsupported (FPGA-only) blocks are dropped either way.
    """
    orig = os.path.join(os.path.dirname(__file__), "sim_server.orig")
    blocks = []
    try:
        with open(orig) as f:
            for ini_path, number, address in _CREATE_BLOCK_RE.findall(f.read()):
                blocks.append((ini_path, int(number), int(address)))
    except OSError:
        blocks = []
    if not blocks:
        blocks = list(FALLBACK_BLOCKS)
    return [
        b
        for b in blocks
        if os.path.basename(b[0]).replace(".block.ini", "") not in UNSUPPORTED_BLOCKS
    ]


def configure_pcap_registers(controller, config_dir):
    """Point the *REG PCAP registers at the sim, using the real offsets.

    Two things are wrong out of the box for a real app config:

    1. ``SimulationController`` hardcodes the *REG PCAP register offsets
       (START_WRITE=8, WRITE=9, ARM=10, DISARM=11). That is only correct for the
       engine's default layout. The ``pandabox-no-fmc`` app inserts optional
       ``PCAP_TS_SEC``/``PCAP_TS_TICKS`` registers, shifting ARM/DISARM to 13/14
       in the generated ``registers`` file the C server actually uses. So a real
       ``*PCAP.ARM=`` writes register 13, which the sim leaves unmapped -> the
       arm is silently dropped and ``PCAP.ACTIVE`` never latches.
    2. The mapped names are prefixed (``PCAP_ARM``), but ``pcap_sim.on_changes``
       only acts on the bare names (``ARM``/``DISARM``/``START_WRITE``/``WRITE``).

    Re-derive the offsets from ``config_d/registers`` and map them to the bare
    names the simulation acts on.
    """
    pcap = getattr(controller, "pcap", None)
    if pcap is None:
        return
    # Drop the engine's hardcoded (and here incorrect) *REG PCAP offsets.
    for key in list(controller.lookup):
        block, name = controller.lookup[key]
        if block is pcap and key[0] == 0 and isinstance(name, str) \
                and name.startswith("PCAP_"):
            del controller.lookup[key]
    wanted = {
        "PCAP_START_WRITE": "START_WRITE",
        "PCAP_WRITE": "WRITE",
        "PCAP_ARM": "ARM",
        "PCAP_DISARM": "DISARM",
    }
    regfile = os.path.join(config_dir, "registers")
    with open(regfile) as f:
        for line in f:
            toks = line.split()
            # Lines look like: "PCAP_ARM 13" or "PCAP_TS_SEC opt 10"
            if len(toks) >= 2 and toks[0] in wanted:
                try:
                    offset = int(toks[-1])
                except ValueError:
                    continue
                controller.lookup[(0, 0, offset)] = (pcap, wanted[toks[0]])


def install_signed_writes(controller, blocks):
    """Sign-extend register writes to fields the block inis declare signed.

    The C server transports every register write as a raw uint32, but the
    Python engine computes in arbitrary-precision ints. A field the app
    declares ``param int`` (PCOMP START/STEP/WIDTH/PRE_START, ...) written
    as e.g. -39460 therefore arrives as 4294927836, and PCOMP's
    ``posn() >= next_crossing`` can never be true: a fly scan over the real
    encoder range (offset -39660) waits forever in WAIT_RISING while the
    positive-range smoke test passes. Wrap ``do_write_register`` to fold
    values back into int32 range for exactly the fields whose ini type
    carries the ``int`` (signed) token.
    """
    signed_by_addr = {}
    for ini_path, _num, addr in blocks:
        cp = configparser.ConfigParser(strict=False, interpolation=None)
        cp.read(os.path.join(_FPGA_ROOT, ini_path))
        fields = set()
        for section in cp.sections():
            if "int" in cp[section].get("type", "").split():
                fields.add(section.upper())
        if fields:
            signed_by_addr[addr] = fields
    signed = set()
    for (addr, _inum, _reg), (block, field) in controller.lookup.items():
        if isinstance(field, str) and \
                field.upper() in signed_by_addr.get(addr, ()):
            signed.add((block, field))

    orig_write = controller.do_write_register

    def do_write_register(block_num, num, reg, value):
        entry = controller.lookup.get((block_num, num, reg))
        if entry and (entry[0], entry[1]) in signed and value >= 0x80000000:
            value -= 0x100000000
        return orig_write(block_num, num, reg, value)

    controller.do_write_register = do_write_register


def build_block_index(controller, blocks):
    """Map PandA block names (e.g. ``INENC1``) to their simulation instances.

    Used by the position-injection channel to resolve a ``<BLOCK> <FIELD>``
    target to the block instance whose field is driven. PandA numbers blocks
    from 1 (``INENC1`` == instance 0), matching the control protocol.
    """
    addr_name = {addr: os.path.basename(ini).replace(".block.ini", "").upper()
                 for ini, _num, addr in blocks}
    index = {}
    for (addr, inum, _reg), (block, _field) in controller.lookup.items():
        if isinstance(block, SimulationController) or addr not in addr_name:
            continue
        index["%s%d" % (addr_name[addr], inum + 1)] = block
    return index


class SocketFail(Exception):
    pass


class Py3SimulationServer:
    """Register-protocol socket server (Python-3 clean).

    Speaks the same 4-byte command protocol as PandABlocks-FPGA's
    `SimulationServer`, delegating all logic to the shared
    `SimulationController` engine.
    """

    def __init__(self, controller, host="localhost", port=9999,
                 inject_port=0, block_index=None):
        self.controller = controller
        self.block_index = block_index or {}
        self.sock_l = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        self.sock_l.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        self.sock_l.bind((host, port))
        self.sock_l.listen(0)
        self.sock = None
        # Optional position-injection channel (a bridge feeds the moving motor
        # position into the sim's encoder input so PCOMP/PULSE/PCAP capture).
        self.inject_l = None
        self.inject_clients = []
        self._inject_buf = {}
        if inject_port:
            self.inject_l = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            self.inject_l.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
            self.inject_l.bind((host, inject_port))
            self.inject_l.listen(4)

    def run(self):
        (self.sock, _addr) = self.sock_l.accept()
        self.sock_l.close()
        self.sock.setsockopt(socket.SOL_TCP, socket.TCP_NODELAY, 1)
        try:
            while True:
                timeout = self.controller.calc_timeout()
                readers = [self.sock]
                if self.inject_l is not None:
                    readers.append(self.inject_l)
                readers.extend(self.inject_clients)
                rlist, _, _ = select.select(readers, (), (), timeout)
                if self.sock in rlist:
                    self._respond()
                if self.inject_l is not None and self.inject_l in rlist:
                    self._accept_inject()
                for client in list(self.inject_clients):
                    if client in rlist:
                        self._handle_inject(client)
                self.controller.do_tick()
        except (KeyboardInterrupt, SocketFail) as e:
            print("Simulation closed: %r" % e)

    def _accept_inject(self):
        client, _addr = self.inject_l.accept()
        client.setsockopt(socket.SOL_TCP, socket.TCP_NODELAY, 1)
        # Non-blocking: a client that stops reading its replies must never
        # stall the engine loop (a blocked sendall here froze the whole sim
        # once the peer's receive buffer filled).
        client.setblocking(False)
        self.inject_clients.append(client)
        self._inject_buf[client] = b""

    def _handle_inject(self, client):
        try:
            chunk = client.recv(4096)
        except (BlockingIOError, InterruptedError):
            return
        except OSError:
            chunk = b""
        if not chunk:
            self.inject_clients.remove(client)
            self._inject_buf.pop(client, None)
            client.close()
            return
        buf = self._inject_buf[client] + chunk
        lines = buf.split(b"\n")
        self._inject_buf[client] = lines.pop()
        for line in lines:
            reply = self._apply_inject(line.decode("ascii", "replace").strip())
            # Replies are best-effort acknowledgements: drop them rather than
            # ever blocking the engine on a peer that is not reading.
            try:
                client.send((reply + "\n").encode())
            except OSError:
                pass

    def _apply_inject(self, line):
        """Apply one ``<BLOCK> <FIELD> <int>`` injection line to the engine."""
        if not line or line.startswith("#"):
            return "OK"
        parts = line.split()
        if len(parts) != 3:
            return "ERR expected '<BLOCK> <FIELD> <int>'"
        name, field, raw = parts
        block = self.block_index.get(name.upper())
        if block is None:
            return "ERR unknown block %s" % name
        try:
            value = int(float(raw))
        except ValueError:
            return "ERR bad value %s" % raw
        # Drive the field as if the block produced it; the engine fans the
        # change out to listeners (CALC/PCOMP) and schedules PCAP.
        self.controller.do_tick({block: {field.upper(): value}})
        return "OK"

    def _read(self, n):
        result = b""
        while len(result) < n:
            rx = self.sock.recv(n - len(result))
            if not rx:
                raise SocketFail("End of input")
            result += rx
        return result

    def _respond(self):
        command_word = self._read(4)
        command, block, num, reg = struct.unpack("cBBB", command_word)
        if command == b"R":
            tx = self.controller.do_read_register(block, num, reg)
            self.sock.sendall(struct.pack("I", tx & 0xFFFFFFFF))
        elif command == b"W":
            (value,) = struct.unpack("I", self._read(4))
            self.controller.do_write_register(block, num, reg, value)
        elif command == b"T":
            (length,) = struct.unpack("I", self._read(4))
            data = self._read(length * 4)
            data = np.frombuffer(data, dtype=np.int32)
            self.controller.do_write_table(block, num, data)
        elif command == b"D":
            (length,) = struct.unpack("I", self._read(4))
            data = self.controller.do_read_capture(length // 4)
            if data is None:
                self.sock.sendall(struct.pack("i", -1))
            else:
                raw = np.ascontiguousarray(data, dtype="<i4").tobytes()
                assert len(raw) <= length
                self.sock.sendall(struct.pack("I", len(raw)))
                self.sock.sendall(raw)
        else:
            raise SocketFail("Unexpected command %r" % command_word)


def main():
    parser = argparse.ArgumentParser(description="PandA Py3 hardware simulation")
    parser.add_argument(
        "-d", "--daemon", action="store_true", help="Run as daemon process"
    )
    parser.add_argument(
        "-v", "--verbose", action="store_true", help="Log register access"
    )
    args = parser.parse_args()

    controller = SimulationController(args.verbose)
    block_list = load_blocks()
    for ini_path, number, block_address in block_list:
        controller.create_block(ini_path, number, block_address)

    config_dir = os.environ.get("PANDA_CONFIG_D") or os.path.join(
        os.path.dirname(__file__), "config_d"
    )
    configure_pcap_registers(controller, config_dir)
    install_signed_writes(controller, block_list)
    block_index = build_block_index(controller, block_list)

    # Position-injection channel (default 9101). A host-side bridge feeds the
    # moving motor position into the encoder input so the capture chain fires.
    inject_port = int(os.environ.get("PANDA_INJECT_PORT", "9101"))

    # Bind the socket BEFORE daemonising so the C server can connect to the
    # inherited listening socket once the launcher returns.
    server = Py3SimulationServer(
        controller, inject_port=inject_port, block_index=block_index
    )

    print("Simulating server ready")
    sys.stdout.flush()
    if args.daemon:
        daemonise()
    server.run()


if __name__ == "__main__":
    main()
